.POSIX:

# This Makefile was generated by maje
# See https://gitlab.com/jkaivo/maje/ for more information
# Do not edit this Makefile by hand

default: all

CC=c99
LD=$(CC)
CFLAGS=-Wall -Wextra -Wpedantic -Werror -g
LDFLAGS=

all: maje

clean:
	rm -f maje *.o

maje: make.o
make.o: make.c
	$(CC) $(CFLAGS) -c make.c

maje: sources.o
sources.o: sources.c
	$(CC) $(CFLAGS) -c sources.c

maje: main.o
main.o: main.c
	$(CC) $(CFLAGS) -c main.c

maje: maje.o
maje.o: maje.c
	$(CC) $(CFLAGS) -c maje.c

maje:
	$(LD) $(LDFLAGS) -o $@ *.o
