#define _XOPEN_SOURCE 700
#include <libgen.h>
#include <string.h>
#include <stdio.h>
#include <stdlib.h>

#include "maje.h"

static void make_header(FILE *makefile, const char *target)
{
	fprintf(makefile, ".POSIX:\n\n");
	fprintf(makefile, "# This Makefile was generated by maje\n");
	fprintf(makefile, "# See https://gitlab.com/jkaivo/maje/ for more information\n");
	fprintf(makefile, "# Do not edit this Makefile by hand\n\n");

	fprintf(makefile, "CC=c99\n");
	fprintf(makefile, "LD=$(CC)\n");
	fprintf(makefile, "CFLAGS=-Wall -Wextra -Wpedantic -Werror -g\n");
	fprintf(makefile, "LDFLAGS=\n");
	fprintf(makefile, "LDLIBS=\n");
	fprintf(makefile, "SRCDIR=.\n");
	fprintf(makefile, "OBJDIR=.\n");
	fprintf(makefile, "BINDIR=$(OBJDIR)\n");
	fprintf(makefile, "\n");

	fprintf(makefile, "all: $(BINDIR)/%s\n\n", target);

	fprintf(makefile, "clean:\n");
	fprintf(makefile, "\trm -f $(BINDIR)/%s $(OBJDIR)/*.o\n\n", target);
}

static void add_object(FILE *makefile, const struct majefile *src, const char *target)
{
	char *fullobj = strdup(src->path);
	char *obj = basename(fullobj);
	obj[strlen(obj) - 1] = 'o';

	fprintf(makefile, "$(BINDIR)/%s: $(OBJDIR)/%s\n", target, obj);
	for (struct majefile *inc = find_includes(src); inc != NULL; inc = inc->next) {
		fprintf(makefile, "$(OBJDIR)/%s: $(SRCDIR)/%s\n",
			obj, inc->path);
	}
	fprintf(makefile, "$(OBJDIR)/%s: $(SRCDIR)/%s\n", obj, src->path);
	fprintf(makefile, "\t$(CC) $(CFLAGS) -o $@ -c $(SRCDIR)/%s\n\n", src->path);

	free(fullobj);
}

void make_makefile(const char *makepath, struct majefile *sources, const char *target)
{
	FILE *makefile = fopen(makepath, "w");
	if (makefile == NULL) {
		perror("fopen: Makefile");
		return;
	}

	make_header(makefile, target);
	for (struct majefile *src = sources; src != NULL; src = src->next) {
		add_object(makefile, src, target);
	}

	fprintf(makefile, "$(BINDIR)/%s:\n", target);
	fprintf(makefile, "\t$(LD) $(LDFLAGS) -o $@ $(OBJDIR)/*.o $(LDLIBS)\n");

	fclose(makefile);
}
